import crypto_conversion_lib as cl

Kraken = cl.Kraken()
print("--------- KRAKEN ---------------")
Kraken.convert_deposits()
print("Deposits = ", Kraken.deposits.columns)
Kraken.convert_trades()
print("Trades = ", Kraken.trades.columns)
Kraken.combine_deposits_trades()
# print("Total = ", Kraken.trade_history.count()[0])

Kraken.save_trade_history("kraken.csv")
print("--------- KUCOIN ---------------")
Kucoin = cl.Kucoin()
Kucoin.convert_deposits()
# print("Deposits = ", Kucoin.deposits.dtypes)
# print("Deposits = ", Kucoin.deposits.count()[0])
Kucoin.convert_trades()
# print("Trades = ", Kucoin.trades.count()[0])
Kucoin.combine_deposits_trades()
# print("Total = ", Kucoin.trade_history.count()[0])
Kucoin.save_trade_history("kucoin.csv")
# # print(Kucoin.trade_history.dtypes)
# print(Kraken.trade_history.iloc[0])

Binance = cl.Binance()
print("--------- BINANCE ---------------")
Binance.convert_deposits()
# print(Binance.deposits.dtypes)
# print("Deposits = ", Binance.deposits.count()[0])
# print(Binance.deposits.iloc[-1])
Binance.convert_trades()
# print("Trades = ", Binance.trades.count()[0])
# print(Binance.trades.iloc[-1])
Binance.combine_deposits_trades()
# print("Total = ", Binance.trade_history.count()[0])
Binance.save_trade_history("binance.csv")